//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Car
{
	private double DailyCost
	{
		get;
		set;
	}

	private double MilageCost
	{
		get;
		set;
	}

	private bool IsRented
	{
		get;
		set;
	}

	private double ExtraInsurance
	{
		get;
		set;
	}

	public virtual Rent Rent
	{
		get;
		set;
	}

	public virtual void setDailyCost(object double)
	{
		throw new System.NotImplementedException();
	}

	public virtual double getDailyCost()
	{
		throw new System.NotImplementedException();
	}

	public virtual double getMilageCost()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setMilageCost(object double)
	{
		throw new System.NotImplementedException();
	}

	public virtual void setExtraInsurance(object double)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getExtraInsurance()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getIsRented()
	{
		throw new System.NotImplementedException();
	}

}

