//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
	private bool IsBlacklisted
	{
		get;
		set;
	}

	private string Name
	{
		get;
		set;
	}

	public virtual Rent Rent
	{
		get;
		set;
	}

	public virtual void setIsBlacklisted(object bool)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getIsBlacklisted()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setName(object string)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getName()
	{
		throw new System.NotImplementedException();
	}

}

