//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
    private bool isBlacklisted = true;

    private string name = "Viktor";

	public Rent Rent
	{
		get;
		set;
	}
    public bool IsBlacklisted()
	{
        return isBlacklisted;
	}

	public string getName()
	{
        return name;
	}
}

