//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
    private bool IsBlacklisted = true;

    private string Name = "Viktor";

	public Rent Rent
	{
		get;
		set;
	}

	public bool getIsBlacklisted()
	{
        return IsBlacklisted;
	}

	public string getName()
	{
        return Name;
	}
}

