//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FamilyCar : Car
{
    double value = 1000;
    public double TotalMilesDriven
    {
        get
        {
            return this.value;
        }
        set
        {
            this.value = value;
        }
    }
}

