//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SportCar : Car
{
    double Value;
    public override double ExtraInsurance
    {
        get
        {
            if (Value > 150)
                return Value;
            else
                return 150;
        }
        set { Value = value; }
    }
}

