//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SportCar : Car
{
    double insurance;
    public override double ExtraInsurance
    {
        get
        {
            if (insurance > 150)
                return insurance;
            else
                return 150;
        }
        set
        {
            insurance = value;
        }
    }

    double miles = 1000;
    public double TotalMilesDriven
    {
        get
        {
            return this.miles;
        }
        set
        {
            this.miles = value;
        }
    }
}

